---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.tunnel.secretName }}
  namespace: networking
spec:
  encryptedData:
    credentials.json: AgA4Tiprm56XABDyKG7ITwaGr5C6+HSQ46N93cHaDv42URSphkbPl7/5TgS6tqez+Uoum4tWmlw+M+JyujFL1URdlF8xclqEhoZYHDnmHhuVG62uo6w9PpQRn2T7ianaabglMJlZnnuZKniAzP5q+N07AgIOKv5aEBkT5ASsCtKuzGuerRU5jz3kChiuA47Gv0nCc7NCSpeR8mtZPQJUJPaArcWgbIf0TP8ceR0eL2kk2p1457ndg/+CREOmbsCBO1n4s9k8a3btYwoTW8JvEo3Mu/j69Lra1FXBMiOcZyEJzV2pyAEKPnVptxK1jsGvS/xhnDHVQEp8HQRgRflCukrmJTSJJmM3xOIHZdCjD8Y6yzjIw5gEwV3/THU3UxsBrVevJwrs9HamnDiNpAg0mwECdWb7pb6IoSrvbv4gMrpxyDYMefPTLc1G9AI1NfeQI3JTLK/HOMCcq9187Ypef/8GYR0ALR/XHNofHarPYq25B3B19QoEOAUNvjVsme3b8AIrNRX0s4XuE0wSLP+rHO8/Sllnmbe00lJVpG5QB5zuUUDimT3HF+WICxUd43xuyUHi6u4o239i8qfNVhDJzd2F5HkjR2KgZdso8WufZiQ0u49X3BUpIGhnPeydjetvQ8FMn3r0cA7Za1WaczoyVHlEfeGr4VnPSJRdm58KRdULjsyyFJz+W/XyV1zXkcd2447mo6hokGXd9N7F8TfDoSBko/DVyhMj06nEODTzRS6OnzdzRehNUrtPS2eKBDwvfoT2SeHLg3uLobuG8xIwFuHX01dzt7zsEpHFMRJVKyxPTHiOmKmfi4JDeFaNZvbkjOcNZ8/QCPwqSemRV7KS7qOKSZ347VslmczakuraRdXzgUzF4m0ja1GDNFhBQQynVNnodjo+eWJOZ+psfGFJnv7qGCcZK+8STsN4zF/OT2nZ
  template:
    metadata:
      name: tunnel-credentials
      namespace: networking
