apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wfbm/framer.git
    path: deploy/charts/cloudflare-tunnel
    targetRevision: HEAD
    helm:
      values: |-
        tunnel:
          secretName: "tunnel-credentials"
          services:
            mapping:
              - hostname: minio.balanlab.dev
                service: http://minio-infra.storage:9000
              - hostname: argo.balanlab.dev
                service: http://argocd-server.argocd
              - hostname: waha.balanlab.dev
                service: http://waha-service.waha:3000
              - service: http_status:404
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

