apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waha
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wfbm/framer.git
    path: deploy/charts/waha
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: waha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
